### ISSUE TITLE
Compile error: definition of unknown language item `panic_fmt`

### ISSUE THREAD

**Issue by trainman419** [pftbest/msp430-rt#2]
According to https://users.rust-lang.org/t/psa-breaking-change-panic-fmt-language-item-removed-in-favor-of-panic-implementation/17875 , panic_fmt has been changed to panic_implementation. It looks like this is causing a compilation error in this crate:

```
error[E0522]: definition of an unknown language item: `panic_fmt`
 --> /home/austin/.cargo/registry/src/github.com-1ecc6299db9ec823/msp430-rt-0.1.2/src/lang_items.rs:3:1
  |
3 | #[lang = "panic_fmt"]
  | ^^^^^^^^^^^^^^^^^^^^^ definition of unknown language item `panic_fmt`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0522`.
error: Could not compile `msp430-rt`.
```

I'm actively playing with this, so I may try to provide a pull request if I can figure out how to fix it.

**Comment by trainman419** [comment]
I'm attempting to fix this, but it seems like something is not quite right. With the changes in https://github.com/pftbest/msp430-rt/compare/master...trainman419:master , I'm getting:

```
error: language item required, but not found: `panic_impl`

error: aborting due to previous error

error: Could not compile `msp430-quickstart`.
```

**Comment by pftbest** [comment]
the proper fix would be to remove all the panic stuff from this crate completely and just create a new crate named panic-loop or something, similar to panic-abort and panic-semihosting crates

**Comment by trainman419** [comment]
Sorry; I'm still a bit of a Rust noob. I updated the Cargo.toml to override the msp430-rt dep from crates.io, and my patches to msp430-rt work now!

Since the panic function is calling msp430-specific functions, it would probably need to be an msp430-panic-loop crate or something similar.

**Comment by trainman419** [comment]
Submitted my changes as: https://github.com/pftbest/msp430-rt/pull/3

**Comment by pftbest** [comment]
Thank you
